FROM eientei/moebooru:iichan-branding
ADD https://cookiewiki.org/images/0/07/Cookiewiki_logo.png /moebooru/app/assets/images/logo.png
RUN convert /moebooru/app/assets/images/logo.png -resize 75x75 /moebooru/app/assets/images/logo_small.png
