version: '3.5'
services:
  moebooru:
    image: "moebooru:latest"
    restart: "unless-stopped"
    depends_on:
      - postgres
      - memcached
    ports:
      - "8080:8080"
    expose:
      - "5500"
      - "5566"
    volumes:
      - "./data-moebooru:/moebooru/public/data"
    environment:
      MB_DATABASE_URL: "postgres://moedb:moedb@postgres:5432/moedb"
      MB_MEMCACHE_SERVERS: "memcached:11211"
      MB_HOST_NAME: "localhost"
      MB_URL_BASE: "http://127.0.0.1:8080"
      MATCH_TRESHOLD: "60"
    entrypoint:
      - "sh"
      - "-c"
      - |
        echo "waiting for postgres..."
        while ! nc -z postgres 5432; do
          sleep 1
          echo -n "."
        done
        echo ""
        echo "waiting for memcached..."
        while ! nc -z memcached 11211; do
          sleep 1
          echo -n "."
        done
        echo ""
        exec /entrypoint.sh
  postgres:
    image: "postgres:9.6"
    restart: "unless-stopped"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "moedb"
      POSTGRES_PASSWORD: "moedb"
      POSTGRES_DB: "moedb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - "5432"
    volumes:
      - "./data-postgres:/var/lib/postgresql/data"
  memcached:
    image: "memcached:latest"
    restart: "unless-stopped"
    expose:
      - "11211"

